### ISSUE TITLE
[feat] admin component / navigation 생성

### ISSUE THREAD

**Issue by rose129** [Think-Tank-6/VOS-client#7]
## 📌 설명
> admin 생성했습니다.

## 🗒️ Todo
- [x] admin.js 생성
- [x] userList.js 생성
- [x] userDetail.js 생성
